permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "Jenny Owens"
  description: |
    This is a pattern library for my portfolio website.
  font_url: "https://fonts.googleapis.com/css?family=Pinyon+Script|Playfair+Display:400,700&display=swap"
  colors:
    background: "--color-secondary"
    patterns:
    rationales:
      typefaces.primary: |
        Playfair Display is light, professial serif font with easy readibility.
      typefaces.secondary : |
        Pinyon Script is a beautiful script font that conveys eloquence and works well for short pieces of text like titles.
      colors.primary : |
        Black is the primary colour.
      colors.secondary : |
        White is the secondary colour.
      color.primary.light : |
        Grey is the light colour.
      color.accent : |
        The accent colour is red.
