  title: "Projects"
  description: |
    The projects page has a grid view of all projects included in this website. Small snippets of information are included in each card. Clicking through directs to more detailed accounts of the project. This page has a large photo banner at the top.
