  title: "CaseStudies"
  description: |
    The case study page represents each project on the website. Users are directed here from the projects page. This page delves into the background of projects, their sketches, etc. The final project will be displayed in the banner atop the screen (either a photo or video).
