title: "Main navigation"
description: |
  The navigation bar is used at the very top all pages. It adjusts to different screen sizes simply and easily. The logo will also direct the user to the homepage.
